config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "/pages/:page" => "pages#show"




  put 'trails/:trail_id/maintenanceticket/:id/mark_completed' => 'maintenancetickets#mark_completed', as: :maintenancetickets_mark_completed


  resources :users
  resources :trails do
    resources :maintenancetickets
  end

  root 'pages#show', page: 'home'

end

app/models/maintenanceticket.rb
class Maintenanceticket < ApplicationRecord
  validates :location, presence: true
  validates :body, presence: true

  belongs_to :trail, optional: true #trying to fix weird form error
end

app/controllers/maintenancetickets_controller.rb
class MaintenanceticketsController < ApplicationController
  def index
    @maintenancetickets = Maintenanceticket.all
  end

  def show
    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.find(params[:id])
  end

  def mark_completed
    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.find(params[:id])
    @maintenanceticket.completed = true
    @maintenanceticket.save
    if @maintenanceticket.completed == true
      flash[:notice] = "Maintenance ticket marked as completed. Good work!"
      redirect_to trail_path(@trail)
    else
      flash[:notice] = "Something went wrong!"
      redirect_to trail_path(@trail)
    end
  end


  def new

    user_can_create?

    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.new
  end

  def destroy
    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.find(params[:id])
    @maintenanceticket.destroy
    redirect_to trail_path(@trail)
    flash[:notice] = "Ticket was Deleted"
  end

  def create
    user_can_create?

    @maintenanceticket = Maintenanceticket.new(maintenanceticket_params)
    @trail = Trail.find(params[:trail_id])
    if @maintenanceticket.save!
      # Says trail must exist??
      flash[:notice] = "Maintenance ticket created!"
      redirect_to trail_path(@trail)
    else
      flash[:alert] = "Maintenance ticket not created"
      render :new
    end
  end

  def update
    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.find(params[:id])
    @maintenanceticket.update_attributes(maintenanceticket_params)
    if @maintenanceticket.save
      flash[:notice] = "Maintenance ticket was updated."
      redirect_to trail_maintenanceticket_path
    else
      flash[:alert] = "Unable to edit."
      render :show
    end
  end

  def edit
    @trail = Trail.find(params[:trail_id])
    @maintenanceticket = Maintenanceticket.find(params[:id])
  end

  private

  def maintenanceticket_params
    params.require(:maintenanceticket).permit(:location, :body, :trail_id, :completed)
  end

  def user_can_create?
    unless user_signed_in?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/views/maintenancetickets/edit.html.erb
<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box">
    <h1 class = 'title-text'>Edit Maintenance Ticket</h1>
  </div>
</div>
<br>


<%= form_for ([@trail, @maintenanceticket]) do |f| %>
  <div class="row">
    <div class="column text-center small-12 large-6 small-centered large-centered">
      <%= f.text_field :location, :placeholder => "Location" %>
      <%= f.text_area :body, :placeholder => "Description", cols: 40, rows: 15 %>
      <%= f.hidden_field :trail_id, :value => @trail.id %>
      <div class="actions">
        <%= f.submit "Edit", :class => 'custom-button' %>
      </div>
      <div class="custom-button-small-alert">
        <%= link_to 'Delete', trail_maintenanceticket_path(@trail, @maintenanceticket), data: {:confirm => 'Are you sure?'}, :method => :delete %>
      </div>
    </div>
  </div>
<% end %>

app/views/maintenancetickets/index.html.erb
<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box">
    <h1 class = 'title-text'>Maintenance Ticket</h1>
  </div>
</div>


<div class="small-12 large-8 small-centered large-centered columns">
  <div class="table-box">
    <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
    </div>
  </div>
</div>

<div class="table-box">
  <div class="small-12 large-8 small-centered large-centered columns">
    <table class = "hover">
      <thead>
        <tr>
          <th width="400">Maintenace Tickets</th>
        </tr>
        <tr>
          <th width="200">Location</th>
          <th width="200">Body</th>
        </tr>
      </thead>

      <tbody>
        <% @maintenancetickets.each do |ticket| %>
          <tr>
            <td> <%= link_to "#{ticket.location}", trail_maintenanceticket_path(ticket)  %> </td>
            <td><%= link_to "#{ticket.body}", trail_maintenanceticket_path(ticket)  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/maintenancetickets/new.html.erb
<%= form_for([@trail, @maintenanceticket]) do |f| %>
  <%= f.text_field :location, :placeholder => "Location" %>
  <%= f.text_field :body, :placeholder => "Description" %>
  <%= f.hidden_field :trail_id, :value => @trail.id %>
  <div class="actions">
    <%= f.submit "Submit", :class => 'custom-button' %>
  </div>
<% end %>

app/views/maintenancetickets/show.html.erb
<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box">
    <h1 class = 'title-text'>Maintenance Ticket </h1>
  </div>
</div>
<br>
<br>

<div class="small-12 large-6 small-centered large-centered columns">
  <div class="weather-box">
      <h4 class="custom-text"><u><%= @maintenanceticket.trail.name %></u></h4>
  </div>
</div>

<div class="small-12 large-6 small-centered large-centered columns">
  <div class="weather-box">
      <h4 class="custom-text"><u>Location</u></h4>
      <p class= "custom-text-weather"><%= @maintenanceticket.location %></p>
  </div>
</div>

<div class="small-12 large-6 small-centered large-centered columns">
  <div class="weather-box">
      <h4 class="custom-text"><u>Description</u></h4>
      <p class= "custom-text-weather"><%= @maintenanceticket.body %></p>
  </div>
</div>

<div class="small-6 large-1 small-centered large-centered columns">
  <div class="ticket-button">
      <%= link_to "Edit", edit_trail_maintenanceticket_path(@trail.id, @maintenanceticket) %>
  </div>
</div>

<div class="small-6 large-2 small-centered large-centered columns">
  <div class="ticket-button">
      <%= link_to("Mark Completed", maintenancetickets_mark_completed_path(@maintenanceticket), :method => :put, :confirm => "Are you sure?") %>
  </div>
</div>