config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "/pages/:page" => "pages#show"




  put 'trails/:trail_id/maintenanceticket/:id/mark_completed' => 'maintenancetickets#mark_completed', as: :maintenancetickets_mark_completed


  resources :users
  resources :trails do
    resources :maintenancetickets
  end

  root 'pages#show', page: 'home'

end

app/models/trail.rb
class Trail < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  validates :address, presence: true
  validates :name, presence: true

  has_many :maintenancetickets

  mount_uploader :picture, TrailsUploaderUploader



end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  def index
    @trails = Trail.all
    @hash = Gmaps4rails.build_markers(@trails) do |trail, marker|
      marker.lat trail.latitude
      marker.lng trail.longitude
      marker.title trail.name
    end
  end

  def show
    @trail = Trail.find(params[:id])

    #Maintenanceticket
    @maintenancetickets = @trail.maintenancetickets
    @maintenancetickets = @maintenancetickets.order(:completed)

    #Map
    @hash = Gmaps4rails.build_markers(@trail) do |trail, marker|
      marker.lat trail.latitude
      marker.lng trail.longitude
      marker.title trail.name
    end

    #Weather
    @weather_summary = ForecastIO.forecast(@trail.latitude, @trail.longitude).currently.summary.downcase
    @weather_temperature = ForecastIO.forecast(@trail.latitude, @trail.longitude).currently.temperature
  end

  def new
    @trail = Trail.new
  end

  def create
    @trail = Trail.new(trail_params)
    if @trail.save
      flash[:notice] = "Trail created!"
      redirect_to trails_path
    else
      flash[:alert] = "Trail not created"
      render :new
    end
  end

  def edit


    @trail = Trail.find(params[:id])

    user_can_edit?
  end

  def update
    @trail = Trail.find(params[:id])
    @trail.update_attributes(trail_params)
    if @trail.save
      flash[:notice] = "Nothing bad happened :)"
      redirect_to trails_path
    else
      flash[:alert] = "Something went wrong"
      render :show
    end
  end

  def destroy
    @trail = Trail.find(params[:id])
    @trail.destroy
    redirect_to trails_path
    flash[:notice] = "Trail was deleted"
  end

  private

  def trail_params
    params.require(:trail).permit(:address, :latitude, :longitude, :length, :name, :description, :creator_id, :picture)
  end

  def user_can_edit?
    unless current_user.id == @trail.creator_id || current_user.role == "admin"
      raise ActionController::RoutingError.new("You must be the trail's creator, or an admin, to edit this trail.")
    end
  end

  ForecastIO.configure do |configuration|
    configuration.api_key = '3005c7b585dcfef488065585a2bee2a3'
  end

end

app/views/trails/edit.html.erb
<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box">
    <h1 class = 'title-text'>Edit <%= @trail.name %></h1>
  </div>
</div>
<br>
<%= simple_form_for @trail do |f| %>
  <div class="row">
    <div class="column text-center small-12 large-6 small-centered large-centered">
      <div class="field">
        <%= f.email_field :name, :placeholder => "Name", autofocus: true %>
      </div>
      <div class="field">
        <%= f.text_field :address, :placeholder => "Address" %>
      </div>
      <div class="field">
        <%= f.number_field :length, :placeholder => "Length (mi.) (optional)" %>
      </div>
      <div class="field">
        <%= f.text_area :description, :placeholder => "Description (optional)", cols: 40, rows: 15 %>
      </div>
    
      <%= f.hidden_field :creator_id, :value => current_user.id %>
      <div class="actions">
        <%= f.submit "Edit", :class => 'custom-button' %>
      </div>
      <div class="custom-button-small-alert">
        <%= link_to 'Delete Trail', trail_path(@trail), data: {:confirm => 'Are you sure?'}, :method => :delete %>
      </div>
    </div>
  </div>
<% end %>

app/views/trails/index.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= ENV['MAPS_KEY'] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box">
    <h1 class = 'title-text'>The Trails</h1>
  </div>
</div>


<div class="small-12 large-8 small-centered large-centered columns">
  <div class="table-box">
    <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
    </div>
  </div>
</div>

<div class="table-box">
  <div class="small-12 large-8 small-centered large-centered columns">
    <table class = "hover">
      <thead>
        <tr>
          <th width="200">Name</th>
          <th width="200">Address</th>
          <th width="200">Length</th>
        </tr>
      </thead>

      <tbody>
        <% @trails.each do |trail| %>
          <tr>
            <td><a href="/trails/<%= trail.id %>"><%= trail.name %></a></td>
            <td><%= trail.address %></td>
            <% if trail.length != nil %>
              <td><%= trail.length %> miles</td>
            <% else %>
              <td>Not specified</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>



<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      mapTypeId: google.maps.MapTypeId.TERRAIN,
      disableDefaultUI: true
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/trails/new.html.erb
<div class="small-12 large-6 small-centered large-centered columns">
  <div class="title-box-trail">
    <h1 class = 'title-text'>Add a Trail</h1>
  </div>
</div>
<br>
<%= simple_form_for @trail do |f| %>
  <div class="row">
    <div class="column text-center small-12 large-6 small-centered large-centered">
      <div class="field">
        <%= f.email_field :name, :placeholder => "Name", autofocus: true %>
      </div>
      <div class="field">
        <%= f.text_field :address, :placeholder => "Address" %>
      </div>
      <div class="field">
        <%= f.number_field :length, :placeholder => "Length (mi.) (optional)" %>
      </div>
      <div class="field">
        <%= f.text_area :description, :placeholder => "Description (optional)", cols: 40, rows: 15 %>
      </div>
      <div>
        <label for="picture" class="button">Upload File</label>
        <input type="file" id="picture" class="show-for-sr">
      </div>
      <%= f.hidden_field :creator_id, :value => current_user.id %>
      <div class="actions">
        <%= f.submit "Submit", :class => 'custom-button' %>
      </div>
    </div>
  </div>
<% end %>

app/views/trails/show.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= ENV['MAPS_KEY'] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<row>
<div class="small-12 large-6 small-centered large-centered columns ">
  <div class="title-box">
    <h1 class = 'title-text'> <%= @trail.name %> </h1>
  </div>
</div>




<% if user_signed_in? && current_user.role == "maintainer" && @maintenancetickets.length == 0 %>
  <div class="small-8 large-3 small-centered large-centered columns">
  <div class="no-ticket-box">
    <p class = 'title-text'>No active maintenance tickets</p>
  </div>
</div>

  <% elsif user_signed_in? && current_user.role == "maintainer" %>
  <div class="small-12 large-6 small-centered large-centered columns">
    <div class="table-header-box">
      <h4 class = 'title-text'>Open Tickets</h4>
    </div>
  </div>

    <div class="table-box-bottom">
      <div class="small-12 large-12 small-centered large-centered columns">
        <table class = "hover">
          <thead>
            <tr>
              <th width="200">Location</th>
              <th width="600">Body</th>
              <th width="100">Completed?</th>
            </tr>
          </thead>

          <tbody>
            <% @maintenancetickets.each do |ticket| %>
              <tr>
                <td> <%= link_to "#{ticket.location}", trail_maintenanceticket_path(ticket.trail, ticket)  %> </td>
                <td><%= link_to "#{ticket.body}", trail_maintenanceticket_path(ticket.trail, ticket)  %></td>
                <td><%= link_to "#{ticket.completed}", trail_maintenanceticket_path(ticket.trail, ticket)  %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

<% end %>

<div class="small-12 large-10 small-centered large-centered columns">
  <div class="map-box">
    <h4 class="custom-text"><u>The Map</u></h4>
    <div style='width: 1200px; length: 800px;'>
      <div id="map" style='width: 1000px; height: 400px;'></div>
    </div>
  </div>
</div>

<div class="small-12 large-2 large-centered columns">
<% if user_signed_in? == true %>
  <ul class="button-group">
    <li><a href='/trails/<%= @trail.id %>/maintenancetickets/new' class="button">Create Ticket</a></li>
    <li><a href="/trails/<%= @trail.id %>/edit" class="button">Edit</a></li>
  </ul>
<% end %>
</div>

<div class="small-12 large-6 small-centered large-centered columns">
  <div class="weather-box">
      <h4 class="custom-text"><u>The Weather</u></h4>
      <p class= "custom-text-weather">It is currently <%= @weather_summary %>, with a temperature of <%= @weather_temperature %>&deg;F</p>
  </div>
</div>

<row>
  <div class="small-12 large-8 columns">
    <div class="show-box">
      <h4 class="custom-text"><u>Description</u></h4>
      <% if @trail.description != '' %>
        <p class = "custom-text-body"> <%= @trail.description %> </p>
      <% else %>
        <p class = "custom-text-body">No description available.</p>
      <% end %>
    </div>
  </div>

  <div class="small-12 large-4 columns">
    <div class="show-box">
      <h4 class="custom-text"><u> The Facts </u></h4>
      <p class = "custom-text-body">Name:     <%= @trail.name %> </p>
      <p class = "custom-text-body">Address:     <%= @trail.address %> </p>
      <% if @trail.length != nil %>
        <p class = "custom-text-body">Length:     <%= @trail.length %> miles</p>
      <% else %>
        <p class = "custom-text-body">Length:     Not specified </p>
      <% end %>
      <p class = "custom-text-body">Lat:     <%= @trail.latitude %> </p>
      <p class = "custom-text-body">Long:     <%= @trail.longitude %> </p>
    </div>
  </div>




</row>




<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      mapTypeId: google.maps.MapTypeId.TERRAIN,
      disableDefaultUI: true
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
     handler.getMap().setZoom(15);
  });
</script>

<%= image_tag @trail.picture %>